### ISSUE TITLE
Drop Git and Mercurial build-time dependencies?

### ISSUE THREAD

**Issue by wking** [tianon/docker-overlay#28]
These date back to the initial 0bd1543 (initial ebuilds copied from my personal overlay, 2013-08-26), but I'm not sure why a non-live ebuild would need them.  I understand the RDEPEND from da7ade59 (git is also a runtime dependency, 2013-09-10), but not why both VCSes are build-time dependencies.  Can you explain why?  Is it because Docker is pulling in some live Go dependencies that aren't packaged for Gentoo?

**Comment by tianon** [comment]
Oh man, I think this one is actually fixed now.  Can you confirm, @wking? :+1:
