### ISSUE TITLE
CONFIG_NETFILTER_XT_MATCH_ADDRTYPE not found in latest sys-kernel/aufs-sources

### ISSUE THREAD

**Issue by asridharan** [tianon/docker-overlay#37]
When I ran "emerge app-emulation/docker" it threw an error saying that the CONFIG_NETFILTER_XT_MATCH_ADDRTYPE  has not been turned on. I couldn't find this flag in the latest kernel sources from sys-kernel/aufs-sources (3.18.4). I turned on the NAT (CONFIG_NF_NAT) flag in the kernel compilation and added the "CONFIG_NETFILTER_XT_MATCH_ADDRTYPE " explicitly and that allowed the installation to go through without a hitch. The daemon seems to start, but haven't tried running any "network app" containers. Not sure if this affects any NAT translations that docker needs to provide network access to the apps.

**Comment by int-index** [comment]
You need to enable `CONFIG_NETFILTER_ADVANCED` so `CONFIG_NETFILTER_XT_MATCH_ADDRTYPE` appears in menuconfig.
