### ISSUE TITLE
Docker 1.6 Emerge Fails With Hardened Gentoo (PIE) Toolchain

### ISSUE THREAD

**Issue by AustinMatherne** [tianon/docker-overlay#40]
This is the line it breaks on because "hack/make/dynbinary" does not exist:
`grep -q -- '-fno-PIC' hack/make/dynbinary || die 'hardened sed failed';`

If I use any of the nopie gcc profiles I am able to emerge 1.6 and I can emerge 1.5 with any profile (PIE or no PIE).

[build.log](https://gist.github.com/AustinMatherne/0352b8774e74f594ef5d)
[environment](https://gist.github.com/AustinMatherne/7690f905a317ae59f43b)
[emerge -pqv =app-emulation-docker-1.6.0::docker](https://gist.github.com/AustinMatherne/8b6feab81eb628f315fe)
[emerge --info =app-emulation-docker-1.6.0::docker](https://gist.github.com/AustinMatherne/405d9277ed441ecc6b4a)

**Comment by tianon** [comment]
I've just pushed a fix in b6fe067 to docker-9999; mind giving it a whirl? :+1:

**Comment by AustinMatherne** [comment]
It works like a charm!

**Comment by tianon** [comment]
Cool, thanks for testing.  Syncing over to 1.6.0 now. :+1:

**Comment by tianon** [comment]
09ee9a5 :metal:
