### ISSUE TITLE
CONFIG_RESOURCE_COUNTERS is removed in new kernel

### ISSUE THREAD

**Issue by s7v7nislands** [tianon/docker-overlay#41]
I have file a bug: https://bugzilla.kernel.org/show_bug.cgi?id=99071

**Comment by tianon** [comment]
https://github.com/docker/docker/blob/7011d9ee8ac4990bfc3bfec422db3ab17abf46f1/contrib/check-config.sh#L186

Our list of kernel dependencies comes from this upstream script -- care to make a PR upstream to remove it? (with links to where/why it was removed, too -- especially if there's a suggested replacement)

**Comment by s7v7nislands** [comment]
https://github.com/docker/docker/issues/13543

**Comment by tianon** [comment]
Fixed by d01ffad792c8a16569e9aff5bb39aad2af5fdc4a, thanks! :+1:
