### ISSUE TITLE
apparmor use flag

### ISSUE THREAD

**Issue by Kagami** [tianon/docker-overlay#43]
Hi.

Could you please add "apparmor" use flag which would add "apparmor" DOCKER_BUILDTAG and appropriate dependency?

I copied 1.7.0 ebuild and tried to do it manually but for some reason build fails with the following error:

```
---> Making bundle: dynbinary (in bundles/1.7.0/dynbinary)
# _/var/build/portage/app-emulation/docker-1.7.0/work/docker-1.7.0/dockerinit
/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lapparmor
collect2: error: ld returned 1 exit status
/usr/lib/go/pkg/tool/linux_amd64/6l: running x86_64-pc-linux-gnu-gcc failed: unsuccessful exit status 0x100
```

Although I have libapparmor 2.8.4 installed. Probably I'm missing something.

**Comment by Kagami** [comment]
`sys-libs/libapparmor +static-libs` solved the problem! Though it would be nice if you add apparmor use flag to your overlay.

**Comment by tianon** [comment]
Oh, thanks for the report!  I didn't realize AppArmor on Gentoo actually had a userbase to be honest, but now I see that there's a pretty decent Wiki page devoted to it even. :+1:

I'll see what I can do about fixing this up -- thanks for the work you've already done digging into it!

**Comment by Kagami** [comment]
Cool, thanks!
