### ISSUE TITLE
Net_Prio and Netprio

### ISSUE THREAD

**Issue by doertedev** [tianon/docker-overlay#46]
https://github.com/tianon/docker-overlay/blob/master/app-emulation/docker/docker-1.8.0.ebuild#L94

Did something get renamed here or is 4.1.4-gentoo a special snowflake? :P

The name it searches for is called:

CONFIG_CGROUP_NET_PRIO

on my machine. Or is my machine a special snowflake? :P

**Comment by alunduil** [comment]
+1

**Comment by doertedev** [comment]
+1
