### ISSUE TITLE
app-emulation/docker: dev-lang/go depend

### ISSUE THREAD

**Issue by mischief** [tianon/docker-overlay#50]
is there a particular reason that app-emulation/docker ebuilds lack a DEPEND on dev-lang/go?

**Comment by mischief** [comment]
additionally the depend should have a subslot operator like `:=` so docker is rebuilt if go changes.

**Comment by tianon** [comment]
It inherits such a thing via the `golang` set of eclasses: https://github.com/tianon/docker-overlay/blob/9c860717f3a60d8c6e0880454f6d1f8824901b31/app-emulation/docker/docker-9999.ebuild#L21

(Although the block above that for the live version doesn't technically do so :innocent:)

**Comment by mischief** [comment]
i see now, thanks for the pointer.
