### ISSUE TITLE
Require runc[apparmor] on docker[apparmor]

### ISSUE THREAD

**Issue by Kagami** [tianon/docker-overlay#52]
Related to #43.
I'm getting

```
rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: apparmor: config provided but apparmor not supported"
```

on docker build/run when docker is built with apparmor flag, but runc not. As far as I can understand, it's caused but [this code](https://github.com/opencontainers/runc/blob/master/libcontainer/apparmor/apparmor_disabled.go). So `docker[+apparmor]` should require `runc[+appramor]`. And maybe other deps such as `containerd` too, I haven't investigated it further.

**Comment by tianon** [comment]
Oh, good catch!  I'll make a commit shortly which should resolve this. :+1:

**Comment by tianon** [comment]
Want to give that a shot? :smile:

**Comment by Kagami** [comment]
Could you update release versions too? Normally I don't build docker from git.

**Comment by tianon** [comment]
Fair enough, applied to 1.11.1 too. :+1:

**Comment by Kagami** [comment]
And runc too :)

**Comment by tianon** [comment]
Already did so on `runc` :wink:  (that one's a symlink)

**Comment by Kagami** [comment]
Rebuilt docker & runc, now it works. Thank you.

**Comment by tianon** [comment]
Woot! :+1:

**Comment by vsoch** [comment]
Heyo! I just started randomly getting an error message that looks like this, and I really need help because most of my work revolves around Docker. Even the standard "hello world" isn't working:

```bash
$ docker run hello-world
ERRO[0001] error waiting for container: context canceled 
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"apparmor: config provided but apparmor not supported\"": unknown.
```
I tried uninstalling and reinstalling Docker via [these docs](https://docs.docker.com/install/linux/docker-ce/ubuntu/) and it didn't make a difference.  I'm on:

```bash
 uname -a
Linux vanessa-ThinkPad-T460s 4.15.0-39-generic #42~16.04.1-Ubuntu SMP Wed Oct 24 17:09:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
Any help would be so greatly appreciated - I literally can't work.

**Comment by jomach** [comment]
@vsoch  I have the same problem, on my problem I know where it cames from. I'm running docker from centos on a suse Distro. Check that..

**Comment by vsoch** [comment]
I was running from Ubuntu 16.04, so likely not that.
