### ISSUE TITLE
docker-bin Manifest?

### ISSUE THREAD

**Issue by TheChymera** [tianon/docker-overlay#53]
I am trying to emerge `pp-emulation/docker-bin` and I get the following:

```
>>> Emerging (1 of 1) app-emulation/docker-bin-1.7.1::docker
!!! A file is not listed in the Manifest: '/usr/local/portage/docker/app-emulation/docker-bin/files/docker-containerd.patch'
```

Why don't you distribute the Manifest?

**Comment by tianon** [comment]
Doh, I forgot that `docker-bin` uses a symlink over to `app-emulation/docker`'s "files" directory -- as you can probably see from the folder not being updated in 2 years (https://github.com/tianon/docker-overlay/tree/b625c37660a1a04095f3565873a66fec1db5762a/app-emulation/docker-bin), so I'm going to just remove it. :disappointed:

Sorry for taking so long to get around to looking into this! :cry:
