### ISSUE TITLE
>app-emulation/docker-1.11 needs >app-emulation/containerd-0.2.2

### ISSUE THREAD

**Issue by alunduil** [tianon/docker-overlay#54]
Can we petition upstream to stop releasing software that isn't usable?  This is starting to get annoying.

**Comment by tianon** [comment]
From upstream's perspective, Docker 1.12 isn't released yet (they don't really count RCs officially), so I expect they'll tag a containerd release soon after 1.12 is GA. (Which is unfortunate, but somewhat understandable IMO.)
