### ISSUE TITLE
Unable to install app-emulation/containerd-0.2.3 because it depends on app-emulation/runc 1.0.0 which is not available?

### ISSUE THREAD

**Issue by damm** [tianon/docker-overlay#58]
I tried bumping the ebuild but it's a 404; so should it depend on 1.0.0_rc1?

**Comment by tianon** [comment]
The current dependency is `>= 1.0.0_rc2`, and there's a separate `docker-runc` package as well which can also satisfy the dependency (and should contain Docker's between-releases patches). :+1:
