### ISSUE TITLE
Total mess with runc and docker-runc. Fix provided

### ISSUE THREAD

**Issue by UralZima** [tianon/docker-overlay#69]
Hello. I use official docker overlay. I have unmasked docker, containerd, runc and docker-runc packages.
All was fine, once I updated docker and it deleted runc and installed docker-runc.
On latest update, it want runc back and results in package block.
containerd-0.2.5 depends on runc, 0.2.5-r1 depends on docker-runc.
docker 17.03.0 depends on runc.
Ok I downgraded containerd to resolve block, now docker container fails to start with
oci runtime error: flag provided but not defined: -console

I read on github issues, that docker is not compatible with runc anymore, but still depend on it.
I resolved it by modifying ebuild and replace runc with docker-runc on DEPEND section.

Please fix docker ebuild to depend on docker-runc

**Comment by tianon** [comment]
Technically, either should be fine -- I personally use `app-emulation/runc` from this overlay successfully with the latest Docker 17.03.0-ce release.  As far as I understand, the `app-emulation/docker-runc` ebuild was introduced to more closely follow the precise commits that Docker upstream has been using of `runc` in newer Docker releases (which haven't had corresponding `runc` releases).

IMO, adding an `||` relation to our `RDEPEND` is probably appropriate, but I'll take a look at the current diff to the `app-emulation/docker` in tree as well to see whether that'll cause any other issues.

**Comment by tianon** [comment]
b82a3b8 should help smooth this out quite a bit :+1:

**Comment by UralZima** [comment]
> Technically, either should be fine -- I personally use app-emulation/runc from this overlay successfully with the latest Docker 17.03.0-ce release

Do you use ~amd64 version? It seems, that 'stable' runc version is still compatible with docker-17.03, but if you unmask it with ~amd64, it is not compatible anymore.

From here: https://github.com/docker/docker/issues/30198  
> The latest runc is incomatible with Docker 1.12.
> You can use the docker-runc (should be installed with docker by default)

> This is a regression in recent runc. Downgrade to (eg. 0.1.1+dfsg1-2)

So it seems old version works, if newer need to use only docker-runc

**Comment by UralZima** [comment]
Also, docker devs said in same issue I created on their repo:
> That's not the case; there is no stable release yet for RunC (it hasn't yet reached 1.0), and docker currently uses fork of the 0.2 branch. This will change once RunC reaches 1.0 and the specs are stable.

So I think it is safe and better to change depend section on docker to docker-runc only, and depend from containerd-0.2.5-r1 (as it also now depends from docker-runc). They will use only their fork till versions 1.0, I think it will take long time to release. stable runc is same as stable docker-runc now, but newer version changes. Debian and ubuntu now depends from docker-runc.
