### ISSUE TITLE
17.06

### ISSUE THREAD

**Issue by tianon** [tianon/docker-overlay#70]
Ouch -- this is going to be fun to reconcile.  With 17.06+, we've moved to https://github.com/docker/docker-ce being the main "joining point" for all the released components of Docker.  So, for `docker-9999.ebuild` we need to decide whether to consume `master` of that repo as-is, or whether to instead try to consume `master` of each of the things it conjoins.

Beyond that, we need to get 17.06.0-ce-rc1 building from that source too.

**Comment by mrueg** [comment]
For now, I would suggest only to use master of docker-ce for -9999. We could decide later if we can split it into moby (engine) and docker-cli at some point.

**Comment by mrueg** [comment]
https://github.com/tianon/docker-overlay/pull/71

I can also see this one moving into app-emulation/docker-ce and provide docker-cli and engine as a separate package.
