### ISSUE TITLE
JSON error starting containers on 17.06

### ISSUE THREAD

**Issue by herbmillerjr** [tianon/docker-overlay#72]
Getting following error when starting containers on any of the 17.06 RCs.

`Error response from daemon: json: cannot unmarshal object into Go struct field Process.capabilities of type []string`

My Go version is 1.8.3.

**Comment by tianon** [comment]
Hmm, that sounds like either a `runc` mismatch or a `containerd` mismatch.  What versions of those two are you running?

**Comment by herbmillerjr** [comment]
app-emulation/containerd-0.2.8
app-emulation/docker-runc-1.0.0_rc2_p20170310

**Comment by herbmillerjr** [comment]
It was runc. Now I'm on app-emulation/docker-runc-1.0.0_rc3_p20170607 and now 17.05 won't start but 17.06 will.
